### ISSUE TITLE
[Feature Request] Larger Embeeding Model

### ISSUE THREAD

**Issue by FlowDownTheRiver** [TsLu1s/ollama-chatbot-interface#1]
https://ollama.com/library/snowflake-arctic-embed2 
can you include this embedding model?

Also fyi in rag_chat.py according to changes in langchain I had to update the import statements like this :
![2024-12-14 17_19_54-Window](https://github.com/user-attachments/assets/93b8e533-2787-42de-b0b2-05a28b7440a3)

**Comment by TsLu1s** [comment]
Hi mate,

Thank you for your suggestions. I understand your concerns with langchain updates, i'm also aware of those, that's why the requirements are static and not flexible. If you are having issues with the imports, you're likely using an incompatible version of langchain (or other) and i would suggest you to run the app on a dedicated env. Further updates will likely come with newer versions, but this static approach will remain.

Regarding your embedding suggestion, i included it, and if you want to add other Ollama embeddings options you just need to reference them in the embeddings_models dict.

**Comment by FlowDownTheRiver** [comment]
@TsLu1s Thank you very much for the update for the embeddings. I had a visual environment and I used the requirements file,I don't know how it happened but somehow I got the updated version of langchain that is why I had to modify the import statements. Anyways I also checked information about the streamlit configuration save for the web UI. 
basically we need to create a ".streamlit" folder in the base directory where "navegation.py" is launched. inside we create a file named "config.toml" . In the UI when we make changes for the theme we can copy and paste the changes inside the "config.toml" file. This saves user preferences. It is a manual way of doing it. Why I did it? Because in my experience the chat creates a white font on white background which makes the text invisible to read,so I had to modify the theme from streamlit settings but in that case user preferences was not saved after each session. 
Here is an example "config.toml" file I am using. Thank you for the project!
[config.zip](https://github.com/user-attachments/files/18140809/config.zip)

**Comment by FlowDownTheRiver** [comment]
> Regarding your embedding suggestion, i included it, and if you want to add other Ollama embeddings options you just need to reference them in the embeddings_models dict.

This is a nice info! Thanks!

**Comment by TsLu1s** [comment]
Are you sure that when having troubles, if you update the source root properties in the css file that doesnt fix the issue? What browser are you using, can i ask?

## Original theme:
:root {
    --primary-color: #374B5D;
    /* Muted Navy */
    --secondary-color: #935F4C;
    /* Tan */
    --background-color: #FFFAE5;
    /* Ivory */
    --text-color: #1B1821;
    /* Black */
    --accent-color: #E0D7C7;
    /* Khaki */
    --highlight-color: #F1E2AD;
    /* Yellow */
    --icon-color: #56382D;
    /* Brown */
}

**Comment by FlowDownTheRiver** [comment]
@TsLu1s I use firefox

**Comment by TsLu1s** [comment]
@FlowDownTheRiver I tried the app in Firefox and didn't have any issue and as i showed you the template colors are well defined and should not be white. Thanks for your config suggestion, but it would be a lot easier for you to change the source colors in style.css, but if you still having that font color issue, just change the style.css here:
"""
#### For font color change (add this)
.stChatMessage p {
    color: black;
}

#### For background chat message (change background-color)
.stChatMessage {
    background-color: var(--background-color);
    border-radius: 10px;
    padding: 1rem;
    margin-bottom: 1rem;
    transition: all 0.3s ease;
}
"""

**Comment by FlowDownTheRiver** [comment]
> @FlowDownTheRiver I tried the app in Firefox and didn't have any issue and as i showed you the template colors are well defined and should not be white. Thanks for your config suggestion, but it would be a lot easier for you to change the source colors in style.css, but if you still having that font color issue, just change the style.css here: """
> #### For font color change (add this)
> 
> .stChatMessage p { color: black; }
> #### For background chat message (change background-color)
> 
> .stChatMessage { background-color: var(--background-color); border-radius: 10px; padding: 1rem; margin-bottom: 1rem; transition: all 0.3s ease; } """

I will check these,thank you very much for pointing out where and what to change. @TsLu1s 
Also I have another question regarding to rag chat and in general. Is it possible for you to add changing model parameters from the UI like context lenght,top-k,top-p,temperature,etc and in rag-chat the context awareness is like 0. Is there anyway for you to go deeper to add something like a memory functionality especially for rag. It is forgetting the previous answer or the context.

**Comment by TsLu1s** [comment]
@FlowDownTheRiver Thank you for your suggestions again. I've absolutely considered adding further RAG customization in the UI, but it comes at a cost of less user friendly experience. 
Regarding adding conversation memory to RAG for document analysis, that would not be optimal, since it would come a at cost of inefficiency, performance impact and redundant responses.

Either way, expect to have some new relevant updates early next year, and if you have further suggestions, feel free to create new issues in the future. 

Glad you're enjoying the app :)

**Comment by FlowDownTheRiver** [comment]
Thank you very much,looking for your further updates along the way.
